### ISSUE TITLE
I found some RTL8710CF devices

### ISSUE THREAD

**Issue by TurkeyMan** [kuba2k2/libretuya#37] opened 2022-11-13 16:56 UTC
I have a bunch of RTL8710CF devices:
![image](https://user-images.githubusercontent.com/1146706/201533889-d5819ead-ae53-4e8e-948c-ff75869c8d0a.png)
![image](https://user-images.githubusercontent.com/1146706/201533902-5a914be4-d8c5-43e8-b34e-ac1e9df2c5a0.png)

It's probably a variant of the existing RTL chips, but this 8710CF is not called out anywhere explicitly...
Can I try these out somehow?

**Comment by kuba2k2** [comment] 2022-11-13 17:01
No, RTL8720CF is different from the already supported RTL8710BN. Support for CF is planned for the future.

**Comment by kuba2k2** [comment] 2023-01-19 17:07
Closing this as duplicate of #44.

**Closed by kuba2k2** 2023-01-19 17:07 UTC
Labels: new platform
